// Jugadors i jugadores de "Et plantes o t'arrisques?".
// [nom, fitxer de stickers/, posició, país, club que el defineix, nota (0-100: com de bo/a és; serveix per
//  ordenar la revelació final i triar l'última carta), [pistes]].
// Les pistes han de ser VERITAT però triades per enganyar (un crack amb una pista que sembla dolenta, o al revés).
window.JUGADORS = [
  ["Lionel Messi", "lionel-messi", "DEL", "Argentina", "Barça", 100, ["Juga a la lliga dels Estats Units", "Va debutar al Barça amb un entrenador holandès"]],
  ["Cristiano Ronaldo", "cristiano-ronaldo", "DEL", "Portugal", "Reial Madrid", 98, ["Juga a la lliga de l'Aràbia Saudita", "Va començar a l'Sporting de Portugal"]],
  ["Ronaldinho", "ronaldinho", "DEL", "Brasil", "Barça", 95, ["Ha jugat al Querétaro de Mèxic", "Va acabar la carrera al Fluminense"]],
  ["Ronaldo Nazário", "ronaldo-nazario", "DEL", "Brasil", "Reial Madrid", 96, ["Ha estat propietari del Reial Valladolid", "Ha jugat a l'Inter i al Milan"]],
  ["Andrés Iniesta", "andres-iniesta", "MIG", "Espanya", "Barça", 94, ["Ha jugat al Japó i als Emirats Àrabs", "Va néixer en un poble de menys de 2.000 habitants"]],
  ["Neymar", "neymar", "DEL", "Brasil", "Barça", 90, ["Ha jugat a l'Aràbia Saudita", "Ha tornat a jugar al Santos"]],
  ["Kylian Mbappé", "kylian-mbappe", "DEL", "França", "Reial Madrid", 95, ["Ha jugat la lliga francesa en un club que no és francès", "Va guanyar un Mundial amb 19 anys"]],
  ["Erling Haaland", "erling-haaland", "DEL", "Noruega", "Manchester City", 93, ["Va néixer a Anglaterra", "Ha jugat al Molde i al Salzburg"]],
  ["Harry Kane", "harry-kane", "DEL", "Anglaterra", "Bayern", 89, ["No va guanyar cap títol fins als 31 anys", "Va estar cedit al Leyton Orient i al Millwall"]],
  ["Lamine Yamal", "lamine-yamal", "DEL", "Espanya", "Barça", 95, ["Va néixer el 2007", "Té una Eurocopa"]],
  ["Karim Benzema", "karim-benzema", "DEL", "França", "Reial Madrid", 90, ["Va estar més de 5 anys sense anar amb la selecció", "Té una Pilota d'Or"]],
  ["Gerard Piqué", "gerard-pique", "DEF", "Espanya", "Barça", 86, ["Va estar cedit al Reial Saragossa", "És propietari de l'FC Andorra"]],
  ["Nacho Fernández", "nacho-fernandez", "DEF", "Espanya", "Reial Madrid", 70, ["Té 6 Champions", "Ha guanyat una Eurocopa"]],
  ["Bojan Krkić", "bojan-krkic", "DEL", "Espanya", "Barça", 68, ["Ha jugat a l'Stoke City", "Ha jugat al Milan, la Roma i l'Ajax"]],
  ["Oleguer Presas", "oleguer-presas", "DEF", "Espanya", "Barça", 64, ["Té una Champions i dues Lligues", "Ha jugat a l'Ajax"]],
  ["Oriol Romeu", "oriol-romeu", "MIG", "Espanya", "Girona", 68, ["Ha jugat al Barça, al Chelsea i al València", "Ha jugat a l'Stuttgart"]],
  ["Philippe Coutinho", "philippe-coutinho", "MIG", "Brasil", "Barça", 76, ["Té una Champions", "El Barça va pagar per ell més de 120 milions"]],
  ["Pierre-Emerick Aubameyang", "pierre-emerick-aubameyang", "DEL", "Gabon", "Arsenal", 80, ["Ha estat màxim golejador de la Bundesliga i de la Premier", "La seva selecció és Gabon"]],
  ["Robert Lewandowski", "robert-lewandowski", "DEL", "Polònia", "Barça", 92, ["No té cap Pilota d'Or", "Va començar en un club modest de Polònia"]],
  ["Rodri", "rodri", "MIG", "Espanya", "Manchester City", 93, ["Ha jugat al Vila-real", "Té una Pilota d'Or"]],
  ["Ousmane Dembélé", "ousmane-dembele", "DEL", "França", "PSG", 92, ["El Barça el va vendre per menys de la meitat del que va pagar", "Té la Pilota d'Or 2025"]],
  ["Isco", "isco", "MIG", "Espanya", "Reial Madrid", 82, ["Té 5 Champions", "Ha jugat al Màlaga i al Sevilla"]],
  ["Thibaut Courtois", "thibaut-courtois", "POR", "Bèlgica", "Reial Madrid", 90, ["Va estar cedit pel Chelsea a l'Atlètic", "És porter"]],
  ["Antoine Griezmann", "antoine-griezmann", "DEL", "França", "Atlètic", 89, ["No ha guanyat mai la Champions", "Va jugar a la Reial Societat"]],
  ["Zlatan Ibrahimović", "zlatan-ibrahimovic", "DEL", "Suècia", "Milan", 90, ["No ha guanyat mai la Champions", "Ha jugat a la lliga dels Estats Units"]],
  ["Francesco Totti", "francesco-totti", "DEL", "Itàlia", "Roma", 91, ["Ha jugat tota la carrera en un sol club", "No ha guanyat mai la Champions"]],
  ["Gianluigi Buffon", "gianluigi-buffon", "POR", "Itàlia", "Juventus", 93, ["Ha jugat a la Serie B", "No ha guanyat mai la Champions"]],
  ["Mohamed Salah", "mohamed-salah", "DEL", "Egipte", "Liverpool", 92, ["El Chelsea el va deixar marxar", "Ha jugat a la Fiorentina i al Basilea"]],
  ["Andreas Christensen", "andreas-christensen", "DEF", "Dinamarca", "Barça", 72, ["Té una Champions", "És danès"]],
  ["Ferran Torres", "ferran-torres", "DEL", "Espanya", "Barça", 78, ["Ha jugat al Manchester City", "Va debutar amb el València amb 17 anys"]],
  ["Pep Guardiola", "pep-guardiola", "MIG", "Espanya", "Barça", 86, ["Ha jugat a Qatar i a Mèxic", "Ha jugat al Brescia"]],
  ["Luuk de Jong", "luuk-de-jong", "DEL", "Països Baixos", "PSV", 70, ["Va marcar dos gols en una final europea", "Ha jugat al Barça"]],
  ["Sergio Busquets", "sergio-busquets", "MIG", "Espanya", "Barça", 92, ["Va jugar a Tercera Divisió", "Ha jugat a la lliga dels Estats Units"]],
  ["Xavi Hernández", "xavi-hernandez", "MIG", "Espanya", "Barça", 94, ["Ha jugat a Qatar", "Ha estat entrenador del Barça"]],
  ["Sergio Ramos", "sergio-ramos", "DEF", "Espanya", "Reial Madrid", 91, ["És el jugador amb més expulsions de la història de la Lliga", "Ha jugat a la lliga mexicana"]],
  ["Raphinha", "raphinha", "DEL", "Brasil", "Barça", 89, ["Ha jugat al Leeds United", "Va jugar al Vitória de Guimarães"]],
  ["Jude Bellingham", "jude-bellingham", "MIG", "Anglaterra", "Reial Madrid", 91, ["Va debutar a la Segona anglesa", "Un club li ha retirat el dorsal"]],
  ["Pau Cubarsí", "pau-cubarsi", "DEF", "Espanya", "Barça", 86, ["Va néixer el 2007", "És d'Estanyol"]],
  ["Julián Quiñones", "julian-quinones", "DEL", "Mèxic", "Al-Qadsiah", 74, ["Va néixer a Colòmbia però juga amb Mèxic", "Juga a l'Aràbia Saudita"]],
  ["Fabián Ruiz", "fabian-ruiz", "MIG", "Espanya", "PSG", 85, ["Ha jugat al Nàpols", "Ha guanyat la Champions amb el PSG"]],
  ["Vinícius Júnior", "vinicius-junior", "DEL", "Brasil", "Reial Madrid", 92, ["No té cap Pilota d'Or", "Va marcar el gol d'una final de Champions"]],
  ["Vitinha", "vitinha", "MIG", "Portugal", "PSG", 89, ["Va estar cedit al Wolverhampton", "Ha guanyat la Champions amb el PSG"]],
  ["Khvicha Kvaratskhelia", "khvicha-kvaratskhelia", "DEL", "Geòrgia", "PSG", 88, ["Ha jugat a la lliga russa", "La seva selecció és Geòrgia"]],
  ["Alèxia Putellas", "alexia-putellas", "MIG", "Espanya", "Barça", 95, ["Té dues Pilotes d'Or", "Va jugar a l'Espanyol i al Llevant"]],
  ["Aitana Bonmatí", "aitana-bonmati", "MIG", "Espanya", "Barça", 96, ["Té més d'una Pilota d'Or", "És de Sant Pere de Ribes"]],
  ["Salma Paralluelo", "salma-paralluelo", "DEL", "Espanya", "Barça", 88, ["De jove competia en atletisme", "Va jugar al Vila-real"]],
  ["Lucy Bronze", "lucy-bronze", "DEF", "Anglaterra", "Chelsea", 87, ["És anglesa", "Ha jugat al Barça"]],
  ["Mariona Caldentey", "mariona-caldentey", "MIG", "Espanya", "Arsenal", 87, ["És mallorquina", "Ha jugat a l'Arsenal"]],
  ["Megan Rapinoe", "megan-rapinoe", "DEL", "Estats Units", "OL Reign", 88, ["Ha jugat a l'Olympique de Lió", "És dels Estats Units"]],
  ["Ewa Pajor", "ewa-pajor", "DEL", "Polònia", "Barça", 89, ["És polonesa", "Va jugar més de 10 anys a Alemanya"]],
  ["Ona Batlle", "ona-batlle", "DEF", "Espanya", "Barça", 86, ["Ha jugat al Manchester United", "Ha jugat al Llevant"]],
  ["Clàudia Pina", "claudia-pina", "DEL", "Espanya", "Barça", 84, ["Va estar cedida al Sevilla", "És de Montcada i Reixac"]],
  ["Misa Rodríguez", "misa-rodriguez", "POR", "Espanya", "Reial Madrid", 82, ["És campiona del món", "És portera"]],
  ["Cata Coll", "cata-coll", "POR", "Espanya", "Barça", 86, ["És campiona del món", "És mallorquina"]]
];
