// Generat amb dades/genera_js.py a partir de Transfermarkt: gols 2025-26 en totes les competicions oficials,
// només amb l'equip indicat. [equip, jugador, línia (POR/DEF/MIG/DAV), posició, gols]
export const TEAMS = [{"key": "barcelona", "name": "Barça", "code": "FCB"}, {"key": "real-madrid", "name": "Real Madrid", "code": "RMA"}, {"key": "atletico", "name": "Atlètic de Madrid", "code": "ATM"}, {"key": "villarreal", "name": "Vila-real", "code": "VIL"}, {"key": "betis", "name": "Betis", "code": "BET"}, {"key": "mallorca", "name": "Mallorca", "code": "MLL"}, {"key": "osasuna", "name": "Osasuna", "code": "OSA"}, {"key": "celta", "name": "Celta", "code": "CEL"}, {"key": "girona", "name": "Girona", "code": "GIR"}, {"key": "espanyol", "name": "Espanyol", "code": "ESP"}, {"key": "real-sociedad", "name": "Reial Societat", "code": "RSO"}];
export const PLAYERS = [
["barcelona", "Joan García", "POR", "Portero", 0],
["barcelona", "Marc ter Stegen", "POR", "Portero", 0],
["barcelona", "Wojciech Szczesny", "POR", "Portero", 0],
["barcelona", "Pau Cubarsí", "DEF", "Defensa central", 1],
["barcelona", "Jules Koundé", "DEF", "Lateral derecho", 3],
["barcelona", "Alejandro Balde", "DEF", "Lateral izquierdo", 0],
["barcelona", "Eric García", "DEF", "Defensa central", 1],
["barcelona", "Gerard Martín", "DEF", "Defensa central", 0],
["barcelona", "Ronald Araujo", "DEF", "Defensa central", 4],
["barcelona", "João Cancelo", "DEF", "Lateral derecho", 2],
["barcelona", "Andreas Christensen", "DEF", "Defensa central", 1],
["barcelona", "Xavi Espart", "DEF", "Lateral derecho", 0],
["barcelona", "Álvaro Cortés", "DEF", "Defensa central", 0],
["barcelona", "Jofre Torrents", "DEF", "Lateral izquierdo", 0],
["barcelona", "Pedri", "MIG", "Mediocentro", 2],
["barcelona", "Fermín López", "MIG", "Mediocentro ofensivo", 13],
["barcelona", "Dani Olmo", "MIG", "Mediocentro ofensivo", 8],
["barcelona", "Frenkie de Jong", "MIG", "Mediocentro", 1],
["barcelona", "Gavi", "MIG", "Mediocentro", 0],
["barcelona", "Marc Bernal", "MIG", "Mediocentro", 5],
["barcelona", "Marc Casadó", "MIG", "Pivote", 0],
["barcelona", "Dro Fernández", "MIG", "Mediocentro ofensivo", 0],
["barcelona", "Tommy Marqués", "MIG", "Pivote", 0],
["barcelona", "Toni Fernández", "MIG", "Mediocentro ofensivo", 0],
["barcelona", "Lamine Yamal", "DAV", "Extremo derecho", 24],
["barcelona", "Raphinha", "DAV", "Delantero centro", 21],
["barcelona", "Ferran Torres", "DAV", "Delantero centro", 21],
["barcelona", "Marcus Rashford", "DAV", "Extremo izquierdo", 14],
["barcelona", "Roony Bardghji", "DAV", "Extremo derecho", 2],
["barcelona", "Robert Lewandowski", "DAV", "Delantero centro", 19],
["real-madrid", "Thibaut Courtois", "POR", "Portero", 0],
["real-madrid", "Andriy Lunin", "POR", "Portero", 0],
["real-madrid", "Trent Alexander-Arnold", "DEF", "Lateral derecho", 0],
["real-madrid", "Dean Huijsen", "DEF", "Defensa central", 2],
["real-madrid", "Álvaro Carreras", "DEF", "Lateral izquierdo", 2],
["real-madrid", "Éder Militão", "DEF", "Defensa central", 2],
["real-madrid", "Raúl Asencio", "DEF", "Defensa central", 2],
["real-madrid", "Víctor Valdepeñas", "DEF", "Defensa central", 0],
["real-madrid", "Fran García", "DEF", "Lateral izquierdo", 1],
["real-madrid", "Antonio Rüdiger", "DEF", "Defensa central", 1],
["real-madrid", "Diego Aguado", "DEF", "Defensa central", 0],
["real-madrid", "Daniel Carvajal", "DEF", "Lateral derecho", 0],
["real-madrid", "Ferland Mendy", "DEF", "Lateral izquierdo", 0],
["real-madrid", "David Alaba", "DEF", "Defensa central", 0],
["real-madrid", "David Jiménez", "DEF", "Lateral derecho", 0],
["real-madrid", "Manu Serrano", "DEF", "Lateral izquierdo", 0],
["real-madrid", "Jude Bellingham", "MIG", "Mediocentro ofensivo", 8],
["real-madrid", "Federico Valverde", "MIG", "Mediocentro", 9],
["real-madrid", "Arda Güler", "MIG", "Mediocentro ofensivo", 6],
["real-madrid", "Aurélien Tchouaméni", "MIG", "Pivote", 2],
["real-madrid", "Eduardo Camavinga", "MIG", "Mediocentro", 2],
["real-madrid", "Thiago Pitarch", "MIG", "Mediocentro", 0],
["real-madrid", "Jorge Cestero", "MIG", "Mediocentro", 0],
["real-madrid", "César Palacios", "MIG", "Mediocentro ofensivo", 0],
["real-madrid", "Dani Ceballos", "MIG", "Mediocentro", 0],
["real-madrid", "Manuel Ángel", "MIG", "Mediocentro", 0],
["real-madrid", "Daniel Mesonero", "MIG", "Mediocentro", 0],
["real-madrid", "Kylian Mbappé", "DAV", "Delantero centro", 42],
["real-madrid", "Vinicius Junior", "DAV", "Extremo izquierdo", 22],
["real-madrid", "Rodrygo", "DAV", "Extremo derecho", 3],
["real-madrid", "Franco Mastantuono", "DAV", "Extremo derecho", 3],
["real-madrid", "Endrick", "DAV", "Delantero centro", 0],
["real-madrid", "Brahim Díaz", "DAV", "Extremo derecho", 2],
["real-madrid", "Gonzalo García", "DAV", "Delantero centro", 8],
["real-madrid", "Daniel Yáñez", "DAV", "Extremo derecho", 0],
["real-madrid", "Álvaro Leiva", "DAV", "Extremo izquierdo", 0],
["atletico", "Jan Oblak", "POR", "Portero", 0],
["atletico", "Juan Musso", "POR", "Portero", 0],
["atletico", "Marc Pubill", "DEF", "Defensa central", 1],
["atletico", "Dávid Hancko", "DEF", "Defensa central", 3],
["atletico", "Matteo Ruggeri", "DEF", "Lateral izquierdo", 0],
["atletico", "Marcos Llorente", "DEF", "Lateral derecho", 4],
["atletico", "Robin Le Normand", "DEF", "Defensa central", 3],
["atletico", "Nahuel Molina", "DEF", "Lateral derecho", 2],
["atletico", "José María Giménez", "DEF", "Defensa central", 1],
["atletico", "Clément Lenglet", "DEF", "Defensa central", 0],
["atletico", "Dani Martinez", "DEF", "Defensa central", 0],
["atletico", "Julio Díaz", "DEF", "Lateral izquierdo", 0],
["atletico", "Javier Boñar", "DEF", "Lateral derecho", 1],
["atletico", "Javi Galán", "DEF", "Lateral izquierdo", 0],
["atletico", "Aleksa Puric", "DEF", "Defensa central", 0],
["atletico", "Pablo Barrios", "MIG", "Mediocentro", 1],
["atletico", "Conor Gallagher", "MIG", "Mediocentro", 3],
["atletico", "Rodrigo Mendoza", "MIG", "Mediocentro", 0],
["atletico", "Johnny Cardoso", "MIG", "Mediocentro", 1],
["atletico", "Thiago Almada", "MIG", "Mediocentro ofensivo", 4],
["atletico", "Obed Vargas", "MIG", "Mediocentro", 0],
["atletico", "Koke", "MIG", "Mediocentro", 2],
["atletico", "Javi Morcillo", "MIG", "Mediocentro", 0],
["atletico", "Rayane Belaid", "MIG", "Mediocentro ofensivo", 0],
["atletico", "Jano Monserrate", "MIG", "Mediocentro ofensivo", 0],
["atletico", "Taufik Seidu", "MIG", "Mediocentro", 0],
["atletico", "Julián Alvarez", "DAV", "Delantero centro", 20],
["atletico", "Álex Baena", "DAV", "Extremo izquierdo", 2],
["atletico", "Giuliano Simeone", "DAV", "Extremo derecho", 7],
["atletico", "Ademola Lookman", "DAV", "Extremo izquierdo", 9],
["atletico", "Giacomo Raspadori", "MIG", "Mediapunta", 2],
["atletico", "Nico González", "DAV", "Extremo izquierdo", 5],
["atletico", "Alexander Sørloth", "DAV", "Delantero centro", 20],
["atletico", "Antoine Griezmann", "MIG", "Mediapunta", 14],
["atletico", "Iker Luque", "DAV", "Extremo derecho", 1],
["atletico", "Miguel Cubo", "DAV", "Delantero centro", 1],
["atletico", "Carlos Martín", "DAV", "Extremo derecho", 0],
["villarreal", "Luiz Júnior", "POR", "Portero", 0],
["villarreal", "Arnau Tenas", "POR", "Portero", 0],
["villarreal", "Diego Conde", "POR", "Portero", 0],
["villarreal", "Renato Veiga", "DEF", "Defensa central", 1],
["villarreal", "Santiago Mouriño", "DEF", "Lateral derecho", 1],
["villarreal", "Rafa Marín", "DEF", "Defensa central", 1],
["villarreal", "Logan Costa", "DEF", "Defensa central", 0],
["villarreal", "Alex Freeman", "DEF", "Lateral derecho", 0],
["villarreal", "Pau Navarro", "DEF", "Defensa central", 0],
["villarreal", "Sergi Cardona", "DEF", "Lateral izquierdo", 1],
["villarreal", "Juan Foyth", "DEF", "Defensa central", 0],
["villarreal", "Willy Kambwala", "DEF", "Defensa central", 0],
["villarreal", "Alfonso Pedraza", "DEF", "Lateral izquierdo", 1],
["villarreal", "Adrià Altimira", "DEF", "Lateral derecho", 0],
["villarreal", "Daniel Budesca", "DEF", "Lateral derecho", 0],
["villarreal", "Pape Gueye", "MIG", "Mediocentro", 5],
["villarreal", "Carlos Macià", "MIG", "Mediocentro", 0],
["villarreal", "Santi Comesaña", "MIG", "Mediocentro", 5],
["villarreal", "Alassane Diatta", "MIG", "Mediocentro", 0],
["villarreal", "Thomas Partey", "MIG", "Pivote", 0],
["villarreal", "Dani Parejo", "MIG", "Mediocentro", 1],
["villarreal", "Alberto Moleiro", "DAV", "Extremo izquierdo", 10],
["villarreal", "Georges Mikautadze", "DAV", "Delantero centro", 15],
["villarreal", "Yéremy Pino", "DAV", "Extremo izquierdo", 0],
["villarreal", "Ilias Akhomach", "DAV", "Extremo derecho", 1],
["villarreal", "Tajon Buchanan", "DAV", "Extremo derecho", 7],
["villarreal", "Manor Solomon", "DAV", "Extremo izquierdo", 1],
["villarreal", "Karl Etta Eyong", "DAV", "Delantero centro", 1],
["villarreal", "Tani Oluwaseyi", "DAV", "Delantero centro", 7],
["villarreal", "Nicolas Pépé", "DAV", "Extremo derecho", 8],
["villarreal", "Ayoze Pérez", "DAV", "Delantero centro", 7],
["villarreal", "Alfon González", "DAV", "Extremo izquierdo", 1],
["villarreal", "Gerard Moreno", "DAV", "Delantero centro", 10],
["villarreal", "Hugo López", "DAV", "Delantero centro", 0],
["villarreal", "Pau Cabanes", "DAV", "Delantero centro", 0],
["betis", "Álvaro Valles", "POR", "Portero", 0],
["betis", "Pau López", "POR", "Portero", 0],
["betis", "Adrián San Miguel", "POR", "Portero", 0],
["betis", "Natan", "DEF", "Defensa central", 0],
["betis", "Valentín Gómez", "DEF", "Defensa central", 1],
["betis", "Ángel Ortiz", "DEF", "Lateral derecho", 1],
["betis", "Junior Firpo", "DEF", "Lateral izquierdo", 0],
["betis", "Diego Llorente", "DEF", "Defensa central", 2],
["betis", "Héctor Bellerín", "DEF", "Lateral derecho", 2],
["betis", "Ricardo Rodríguez", "DEF", "Lateral izquierdo", 0],
["betis", "Marc Bartra", "DEF", "Defensa central", 1],
["betis", "Darling Bladi", "DEF", "Lateral izquierdo", 0],
["betis", "Sergi Altimira", "MIG", "Pivote", 2],
["betis", "Nelson Deossa", "MIG", "Mediocentro", 0],
["betis", "Pablo Fornals", "MIG", "Mediocentro", 9],
["betis", "Sofyan Amrabat", "MIG", "Pivote", 1],
["betis", "Giovani Lo Celso", "MIG", "Mediocentro ofensivo", 3],
["betis", "Álvaro Fidalgo", "MIG", "Mediocentro", 1],
["betis", "Marc Roca", "MIG", "Pivote", 1],
["betis", "Isco", "MIG", "Mediocentro ofensivo", 1],
["betis", "Dani Pérez", "MIG", "Mediocentro ofensivo", 0],
["betis", "Iván Corralejo", "MIG", "Mediocentro ofensivo", 0],
["betis", "Antony", "DAV", "Extremo derecho", 14],
["betis", "Abde Ezzalzouli", "DAV", "Extremo izquierdo", 15],
["betis", "Cucho Hernández", "DAV", "Delantero centro", 15],
["betis", "Pablo García", "DAV", "Extremo derecho", 2],
["betis", "Rodrigo Riquelme", "DAV", "Extremo izquierdo", 7],
["betis", "Aitor Ruibal", "DAV", "Extremo derecho", 5],
["betis", "José Antonio Morante", "DAV", "Extremo derecho", 0],
["betis", "Chimy Ávila", "DAV", "Delantero centro", 3],
["betis", "Cédric Bakambu", "DAV", "Delantero centro", 4],
["mallorca", "Leo Román", "POR", "Portero", 0],
["mallorca", "Lucas Bergström", "POR", "Portero", 0],
["mallorca", "Iván Cuéllar", "POR", "Portero", 0],
["mallorca", "Marash Kumbulla", "DEF", "Defensa central", 0],
["mallorca", "Martin Valjent", "DEF", "Defensa central", 0],
["mallorca", "Pablo Maffeo", "DEF", "Lateral derecho", 1],
["mallorca", "Johan Mojica", "DEF", "Lateral izquierdo", 0],
["mallorca", "Mateu Morey", "DEF", "Lateral derecho", 1],
["mallorca", "Toni Lato", "DEF", "Lateral izquierdo", 0],
["mallorca", "David López", "DEF", "Defensa central", 0],
["mallorca", "Antonio Raíllo", "DEF", "Defensa central", 0],
["mallorca", "Miguel Calatayud", "DEF", "Lateral derecho", 0],
["mallorca", "Javier Olaizola", "DEF", "Defensa central", 0],
["mallorca", "Luis Orejuela", "DEF", "Lateral izquierdo", 0],
["mallorca", "Iliesse Salhi", "DEF", "Lateral izquierdo", 0],
["mallorca", "Samú Costa", "MIG", "Pivote", 7],
["mallorca", "Pablo Torre", "MIG", "Mediocentro ofensivo", 4],
["mallorca", "Manu Morlanes", "MIG", "Mediocentro", 3],
["mallorca", "Sergi Darder", "MIG", "Mediocentro", 1],
["mallorca", "Antonio Sánchez", "MIG", "Mediocentro", 0],
["mallorca", "Omar Mascarell", "MIG", "Pivote", 2],
["mallorca", "Jan Salas", "MIG", "Mediocentro", 0],
["mallorca", "Dani Rodríguez", "MIG", "Mediocentro ofensivo", 0],
["mallorca", "Jan Virgili", "DAV", "Extremo izquierdo", 2],
["mallorca", "Vedat Muriqi", "DAV", "Delantero centro", 23],
["mallorca", "Mateo Joseph", "DAV", "Delantero centro", 2],
["mallorca", "Zito Luvumbo", "DAV", "Extremo derecho", 0],
["mallorca", "Takuma Asano", "DAV", "Extremo derecho", 1],
["mallorca", "Marc Domènech", "DAV", "Delantero centro", 0],
["mallorca", "Javi Llabrés", "DAV", "Extremo izquierdo", 1],
["mallorca", "Abdón Prats", "DAV", "Delantero centro", 4],
["mallorca", "Justin Kalumba", "DAV", "Extremo derecho", 0],
["osasuna", "Sergio Herrera", "POR", "Portero", 0],
["osasuna", "Aitor Fernández", "POR", "Portero", 0],
["osasuna", "Enzo Boyomo", "DEF", "Defensa central", 1],
["osasuna", "Jorge Herrando", "DEF", "Defensa central", 0],
["osasuna", "Abel Bretones", "DEF", "Lateral izquierdo", 1],
["osasuna", "Valentin Rosier", "DEF", "Lateral derecho", 1],
["osasuna", "Alejandro Catena", "DEF", "Defensa central", 3],
["osasuna", "Iñigo Arguibide", "DEF", "Lateral derecho", 0],
["osasuna", "Javi Galán", "DEF", "Lateral izquierdo", 0],
["osasuna", "Juan Cruz", "DEF", "Lateral izquierdo", 0],
["osasuna", "Raúl Chasco", "DEF", "Lateral izquierdo", 0],
["osasuna", "Mikel Serrano", "DEF", "Defensa central", 0],
["osasuna", "Aimar Oroz", "MIG", "Mediocentro ofensivo", 0],
["osasuna", "Jon Moncayola", "MIG", "Mediocentro", 1],
["osasuna", "Lucas Torró", "MIG", "Pivote", 0],
["osasuna", "Iker Muñoz", "MIG", "Pivote", 0],
["osasuna", "Asier Osambela", "MIG", "Mediocentro", 2],
["osasuna", "Moi Gómez", "MIG", "Mediocentro ofensivo", 1],
["osasuna", "Jon García", "MIG", "Mediocentro", 0],
["osasuna", "Mauro Echegoyen", "MIG", "Mediocentro", 0],
["osasuna", "Víctor Muñoz", "DAV", "Extremo izquierdo", 7],
["osasuna", "Raúl Moro", "DAV", "Extremo izquierdo", 0],
["osasuna", "Raúl García", "DAV", "Delantero centro", 14],
["osasuna", "Ante Budimir", "DAV", "Delantero centro", 19],
["osasuna", "Sheraldo Becker", "DAV", "Extremo izquierdo", 1],
["osasuna", "Rubén García", "DAV", "Extremo derecho", 2],
["osasuna", "Iker Benito", "DAV", "Extremo derecho", 1],
["osasuna", "Kike Barja", "DAV", "Extremo derecho", 3],
["osasuna", "Roberto Arroyo", "DAV", "Delantero centro", 0],
["osasuna", "Martin Pedroarena", "DAV", "Delantero centro", 0],
["celta", "Ionuț Radu", "POR", "Portero", 0],
["celta", "Iván Villar", "POR", "Portero", 0],
["celta", "Óscar Mingueza", "DEF", "Lateral derecho", 1],
["celta", "Javi Rodríguez", "DEF", "Defensa central", 0],
["celta", "Sergio Carreira", "DEF", "Lateral derecho", 2],
["celta", "Yoel Lago", "DEF", "Defensa central", 1],
["celta", "Javi Rueda", "DEF", "Lateral derecho", 4],
["celta", "Carl Starfelt", "DEF", "Defensa central", 1],
["celta", "Álvaro Núñez", "DEF", "Lateral derecho", 0],
["celta", "Carlos Domínguez", "DEF", "Defensa central", 0],
["celta", "Manu Fernández", "DEF", "Defensa central", 0],
["celta", "Marcos Alonso", "DEF", "Defensa central", 1],
["celta", "Joseph Aidoo", "DEF", "Defensa central", 0],
["celta", "Mihailo Ristic", "DEF", "Lateral izquierdo", 0],
["celta", "Pablo Meixús", "DEF", "Defensa central", 0],
["celta", "Fer López", "MIG", "Mediocentro ofensivo", 2],
["celta", "Ilaix Moriba", "MIG", "Mediocentro", 2],
["celta", "Miguel Román", "MIG", "Mediocentro", 1],
["celta", "Hugo Sotelo", "MIG", "Mediocentro", 0],
["celta", "Fran Beltrán", "MIG", "Mediocentro", 0],
["celta", "Hugo Burcio", "MIG", "Mediocentro", 0],
["celta", "Andrés Antañón", "MIG", "Mediocentro", 0],
["celta", "Damián Rodríguez", "MIG", "Pivote", 1],
["celta", "Matías Vecino", "MIG", "Mediocentro", 0],
["celta", "Óscar Marcos", "MIG", "Mediocentro ofensivo", 1],
["celta", "Williot Swedberg", "DAV", "Extremo izquierdo", 10],
["celta", "Ferran Jutglà", "DAV", "Extremo derecho", 10],
["celta", "Bryan Zaragoza", "DAV", "Extremo izquierdo", 2],
["celta", "Hugo Álvarez", "DAV", "Extremo izquierdo", 4],
["celta", "Jones El-Abdellaoui", "DAV", "Extremo derecho", 3],
["celta", "Pablo Durán", "DAV", "Delantero centro", 5],
["celta", "Hugo González", "DAV", "Extremo derecho", 0],
["celta", "Borja Iglesias", "DAV", "Delantero centro", 18],
["celta", "Iago Aspas", "DAV", "Delantero centro", 8],
["celta", "Franco Cervi", "DAV", "Extremo izquierdo", 0],
["celta", "Ángel Arcos", "DAV", "Extremo izquierdo", 0],
["girona", "Marc ter Stegen", "POR", "Portero", 0],
["girona", "Paulo Gazzaniga", "POR", "Portero", 0],
["girona", "Vladyslav Krapyvtsov", "POR", "Portero", 0],
["girona", "Vitor Reis", "DEF", "Defensa central", 1],
["girona", "Ladislav Krejci", "DEF", "Defensa central", 0],
["girona", "Arnau Martínez", "DEF", "Lateral derecho", 2],
["girona", "Hugo Rincón", "DEF", "Lateral derecho", 1],
["girona", "Alejandro Francés", "DEF", "Defensa central", 0],
["girona", "Álex Moreno", "DEF", "Lateral izquierdo", 0],
["girona", "Daley Blind", "DEF", "Defensa central", 0],
["girona", "David López", "DEF", "Defensa central", 0],
["girona", "Antonio Salguero", "DEF", "Defensa central", 0],
["girona", "Gibert Jordana", "DEF", "Lateral derecho", 0],
["girona", "Pol Arnau", "DEF", "Lateral derecho", 0],
["girona", "Azzedine Ounahi", "MIG", "Mediocentro", 5],
["girona", "Claudio Echeverri", "MIG", "Mediocentro ofensivo", 1],
["girona", "Jhon Solís", "MIG", "Mediocentro", 0],
["girona", "Yangel Herrera", "MIG", "Mediocentro", 0],
["girona", "Fran Beltrán", "MIG", "Mediocentro", 1],
["girona", "Iván Martín", "MIG", "Mediocentro", 0],
["girona", "Thomas Lemar", "MIG", "Mediocentro ofensivo", 3],
["girona", "Donny van de Beek", "MIG", "Mediocentro", 0],
["girona", "Axel Witsel", "MIG", "Pivote", 1],
["girona", "Lass Kourouma", "MIG", "Mediocentro", 0],
["girona", "Javi Sarasa", "MIG", "Mediocentro", 0],
["girona", "Viktor Tsygankov", "DAV", "Extremo derecho", 7],
["girona", "Yáser Asprilla", "DAV", "Extremo derecho", 1],
["girona", "Vladyslav Vanat", "DAV", "Delantero centro", 10],
["girona", "Joel Roca", "DAV", "Extremo izquierdo", 3],
["girona", "Bryan Gil", "DAV", "Extremo izquierdo", 0],
["girona", "Bojan Miovski", "DAV", "Delantero centro", 0],
["girona", "Dawda Camara", "DAV", "Delantero centro", 0],
["girona", "Abel Ruiz", "DAV", "Delantero centro", 0],
["girona", "Portu", "DAV", "Extremo derecho", 0],
["girona", "Cristhian Stuani", "DAV", "Delantero centro", 6],
["girona", "Papa Ba", "DAV", "Extremo derecho", 0],
["girona", "Juan Arango", "DAV", "Extremo izquierdo", 0],
["espanyol", "Marko Dmitrovic", "POR", "Portero", 0],
["espanyol", "Ángel Fortuño", "POR", "Portero", 0],
["espanyol", "Carlos Romero", "DEF", "Lateral izquierdo", 6],
["espanyol", "Omar El Hilali", "DEF", "Lateral derecho", 0],
["espanyol", "Clemens Riedel", "DEF", "Defensa central", 0],
["espanyol", "Fernando Calero", "DEF", "Defensa central", 0],
["espanyol", "José Salinas", "DEF", "Lateral izquierdo", 0],
["espanyol", "Rubén Sánchez", "DEF", "Lateral derecho", 0],
["espanyol", "Miguel Rubio", "DEF", "Defensa central", 1],
["espanyol", "Leandro Cabrera", "DEF", "Defensa central", 3],
["espanyol", "Urko González de Zárate", "MIG", "Pivote", 0],
["espanyol", "Javi Hernández", "MIG", "Mediocentro ofensivo", 0],
["espanyol", "Pol Lozano", "MIG", "Mediocentro", 2],
["espanyol", "Edu Expósito", "MIG", "Mediocentro", 1],
["espanyol", "Ramón Terrats", "MIG", "Mediocentro", 1],
["espanyol", "Charles Pickel", "MIG", "Pivote", 1],
["espanyol", "Ferran Gómez", "MIG", "Mediocentro", 0],
["espanyol", "Roberto Fernández", "DAV", "Delantero centro", 7],
["espanyol", "Luca Koleosho", "DAV", "Extremo derecho", 0],
["espanyol", "Tyrhys Dolan", "DAV", "Extremo derecho", 2],
["espanyol", "Javi Puado", "DAV", "Extremo izquierdo", 2],
["espanyol", "Cyril Ngonge", "DAV", "Extremo derecho", 0],
["espanyol", "Jofre Carreras", "DAV", "Extremo derecho", 1],
["espanyol", "Lluc Castell", "DAV", "Extremo izquierdo", 0],
["espanyol", "Antoniu Roca", "DAV", "Extremo derecho", 0],
["espanyol", "Pere Milla", "DAV", "Extremo izquierdo", 7],
["espanyol", "Kike García", "DAV", "Delantero centro", 10],
["real-sociedad", "Álex Remiro", "POR", "Portero", 0],
["real-sociedad", "Unai Marrero", "POR", "Portero", 0],
["real-sociedad", "Jon Martín", "DEF", "Defensa central", 2],
["real-sociedad", "Jon Aramburu", "DEF", "Lateral derecho", 1],
["real-sociedad", "Sergio Gómez", "DEF", "Lateral izquierdo", 0],
["real-sociedad", "Igor Zubeldia", "DEF", "Defensa central", 1],
["real-sociedad", "Duje Caleta-Car", "DEF", "Defensa central", 1],
["real-sociedad", "Aihen Muñoz", "DEF", "Lateral izquierdo", 1],
["real-sociedad", "Luken Beitia", "DEF", "Defensa central", 0],
["real-sociedad", "Aritz Elustondo", "DEF", "Defensa central", 0],
["real-sociedad", "Álvaro Odriozola", "DEF", "Lateral derecho", 1],
["real-sociedad", "Iñaki Rupérez", "DEF", "Lateral derecho", 0],
["real-sociedad", "Jon Gorrotxategi", "MIG", "Pivote", 1],
["real-sociedad", "Luka Sucic", "MIG", "Mediocentro", 4],
["real-sociedad", "Urko González de Zárate", "MIG", "Pivote", 0],
["real-sociedad", "Beñat Turrientes", "MIG", "Mediocentro", 3],
["real-sociedad", "Arsen Zakharyan", "MIG", "Mediocentro ofensivo", 1],
["real-sociedad", "Pablo Marín", "MIG", "Mediocentro ofensivo", 1],
["real-sociedad", "Carlos Soler", "MIG", "Mediocentro", 4],
["real-sociedad", "Brais Méndez", "MIG", "Mediocentro ofensivo", 6],
["real-sociedad", "Yangel Herrera", "MIG", "Mediocentro", 0],
["real-sociedad", "Ibai Aguirre", "MIG", "Mediocentro", 0],
["real-sociedad", "Mikel Goti", "MIG", "Mediocentro ofensivo", 2],
["real-sociedad", "Mikel Oyarzabal", "DAV", "Delantero centro", 18],
["real-sociedad", "Orri Óskarsson", "DAV", "Delantero centro", 10],
["real-sociedad", "Takefusa Kubo", "DAV", "Extremo derecho", 2],
["real-sociedad", "Ander Barrenetxea", "DAV", "Extremo izquierdo", 4],
["real-sociedad", "Gonçalo Guedes", "DAV", "Extremo izquierdo", 9],
["real-sociedad", "Job Ochieng", "DAV", "Extremo derecho", 0],
["real-sociedad", "Gorka Carrera", "DAV", "Delantero centro", 0],
["real-sociedad", "Wesley", "DAV", "Extremo izquierdo", 0],
["real-sociedad", "Umar Sadiq", "DAV", "Delantero centro", 1],
["real-sociedad", "Lander Astiazaran", "DAV", "Extremo derecho", 0],
["real-sociedad", "Dani Díaz", "DAV", "Extremo derecho", 0],
["real-sociedad", "Jon Karrikaburu", "DAV", "Delantero centro", 0],
["real-sociedad", "Arkaitz Mariezkurrena", "DAV", "Extremo izquierdo", 0]
];
